env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
    - go mod download
gomod:
  proxy: true
builds:
- env:
    - CGO_ENABLED=0
  goos:
    - darwin
    - linux
    - windows
  goarch:
    - 386
    - amd64
    - arm
    - arm64
    - ppc64le
    - s390x
  ignore:
    - goos: darwin
      goarch: 386
    - goos: darwin
      goarch: arm
    - goos: darwin
      goarch: ppc64le
    - goos: darwin
      goarch: s390x
    - goos: windows
      goarch: ppc64le
    - goos: windows
      goarch: s390x
  mod_timestamp: '{{ .CommitTimestamp }}'
  flags:
    - -trimpath
  ldflags:
    - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}}
checksum:
  name_template: '{{ .ProjectName }}-checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - Merge pull request
    - Merge branch
    - go mod tidy
archives:
  - format: binary
    name_template: '{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}'
